# Generated by Django 5.1 on 2025-01-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_order_paymentstatus_product_orderitem_addtocart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='subdistrict',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='village',
            field=models.CharField(default='no', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
