# Generated by Django 5.1 on 2025-02-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_rename_city_shippingaddress_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='address_line1',
            field=models.CharField(default='unknown address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(default='unknown district', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='unknown full name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='unknown number', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='unknown postal code', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='unknown state', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='subdistrict',
            field=models.CharField(default='unknown subdistrict', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='village',
            field=models.CharField(default='unknown village', max_length=100),
            preserve_default=False,
        ),
    ]
