# Generated by Django 5.1 on 2025-02-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_remove_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subdistrict',
        ),
        migrations.RemoveField(
            model_name='order',
            name='village',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_details',
            field=models.TextField(default='unknown shippind details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=50),
        ),
    ]
